const TYPE = {
  TEXT: [
    "Contains",
    "Does Not Contain",
    "Begins With",
    "Ends With",
    "Is Equal To",
  ],
  NUMERIC: [
    "Contains",
    "Does Not Contain",
    "Begins With",
    "Ends With",
    "Is Equal To",
    "Is Less Than",
    "Is Less Than or Equal To",
    "Is More Than",
    "Is More Than or Equal To",
  ],
};

export const Fields = [
  {
    name: "Method",
    value: "method",
    type: TYPE.TEXT,
    values: [
      "TDD",
      "BDD",
      "Pair Programming",
      "Planning Poker",
      "Daily Standup Meetings",
      "Story Boards",
      "User Story Mapping",
      "Continuous Integration",
      "Retrospectives",
      "Burn-down Charts",
      "Requirements Prioritisation",
      "Version Control",
      "Code Sharing",
    ],
  },
  {
    name: "Methodology",
    value: "methodology",
    type: TYPE.TEXT,
    values: [
      "Agile",
      "Scrum",
      "Waterfall",
      "Spiral",
      "XP",
      "Rational Unified Process",
      "Crystal",
      "Clean Room",
      "Feature Driven Development",
      "Model Driven Development",
      "Domain Driven Development",
      "Formal Methods",
      "Problem Driven Development",
      "Cloud Computing",
      "Service Oriented Development",
      "Aspect Oriented Development",
      "Value Driven Development",
      "Product Driven Development",
    ],
  },
  {
    name: "Research Method",
    value: "research_method",
    type: TYPE.TEXT,
    values: [
      "Case Study",
      "Field Observation",
      "Experiment",
      "Interview",
      "Survey",
    ],
  },
  {
    name: "Research Participants",
    value: "research_participants",
    type: TYPE.TEXT,
    values: ["Undergraduates", "Postgraduates", "Practitioners"],
  },
];
